
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGB_Beta1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Agendamentos
{

    public int Id { get; set; }

    public string Diadasemana { get; set; }

    public string Animal { get; set; }

    public string Proprietario { get; set; }

    public string Fone { get; set; }

    public string Banho { get; set; }

    public Nullable<System.DateTime> Chegada { get; set; }

    public Nullable<System.DateTime> Saida { get; set; }

    public string Observacao { get; set; }

    public Nullable<decimal> Total { get; set; }

}

}
