
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGB_Beta1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ControlEntSai
{

    public int Id { get; set; }

    public Nullable<System.DateTime> Data { get; set; }

    public string Historico { get; set; }

    public Nullable<decimal> Entrada { get; set; }

    public Nullable<decimal> Saida { get; set; }

    public Nullable<decimal> SaldoAnterior { get; set; }

}

}
