
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGB_Beta1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PedidoFechado
{

    public int ID { get; set; }

    public Nullable<int> codigoProduto { get; set; }

    public string produto { get; set; }

    public string valor { get; set; }

    public Nullable<int> quantidade { get; set; }

    public string desconto { get; set; }

    public string valorTotal { get; set; }

    public Nullable<System.DateTime> data { get; set; }

    public string cliente { get; set; }

}

}
