
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGB_Beta1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Produtos
{

    public int Id { get; set; }

    public string Codigo { get; set; }

    public string Descricao { get; set; }

    public Nullable<int> Quantidade { get; set; }

    public Nullable<decimal> Valor { get; set; }

    public Nullable<System.DateTime> Validade { get; set; }

    public Nullable<int> ICMS { get; set; }

    public Nullable<int> Unidade { get; set; }

    public string Observacao { get; set; }

}

}
