

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGB_Beta1.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SGBEntities : DbContext
{
    public SGBEntities()
        : base("name=SGBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Agendamentos> Agendamentos { get; set; }

    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<Clientes> Clientes { get; set; }

    public virtual DbSet<ContasApagar> ContasApagar { get; set; }

    public virtual DbSet<Contratos> Contratos { get; set; }

    public virtual DbSet<ControlEntSai> ControlEntSai { get; set; }

    public virtual DbSet<Pedido> Pedido { get; set; }

    public virtual DbSet<PedidoFechado> PedidoFechado { get; set; }

    public virtual DbSet<Produtos> Produtos { get; set; }

    public virtual DbSet<Saidas> Saidas { get; set; }

    public virtual DbSet<Table> Table { get; set; }

    public virtual DbSet<Vacinas> Vacinas { get; set; }

    public virtual DbSet<Vendas> Vendas { get; set; }

    public virtual DbSet<VendasPorData> VendasPorData { get; set; }

}

}

