
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGB_Beta1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Vacinas
{

    public int Id { get; set; }

    public string Vacinas1 { get; set; }

    public string Animal { get; set; }

    public Nullable<int> Idade { get; set; }

    public string Fone { get; set; }

    public string Observacao { get; set; }

    public string Proprietario { get; set; }

}

}
