
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SGB_Beta1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Vendas
{

    public int codigoVenda { get; set; }

    public int codigoProduto { get; set; }

    public string descricao { get; set; }

    public string valor { get; set; }

    public Nullable<int> quantia { get; set; }

    public string valorTotal { get; set; }

    public Nullable<int> pedido { get; set; }

    public Nullable<int> pedidoFechado { get; set; }

    public string formaPagamento { get; set; }

    public string cliente { get; set; }

    public Nullable<System.DateTime> DataVenda { get; set; }

    public string Observacao { get; set; }

}

}
